<?php
return array(
  'mandatory' => array(
    'site_name',
    'base_url',
    'base_dir',
    'client_id',
    'client_secret',
    'box_root_folder_id',
    'username',
    'email',
    'password',
    'general_access_code',
    'google_auth',
  ),
  'optional' => array(
    'site_description' => 'Just another mellery site',
    'home_page' => '',
    'disqus_shortname' => '',
    'cdn_url' => '',
  ),
  'preset' => array(
    'w_max' => '300',
    'h_max' => '300',
    'limit' => '25',
    'expire_image' => '86400',
    'expire_session' => '1800',
    'https' => '0',
    'cache_expire' => '1',
    'usemap' => '1',
    'cache_clean' => '1',
    'retry' => '5',
    'lock_timeout' => '60',
    'use_cdn' => '0',
    'thumb_cdn' => '1',
    'nolicense' => '0',
    'sa' => '0',
    'nc' => '0',
    'allow_se' => '1',
  ),
  'fix' => array(
    'admin_folder_limit' => '25',
    'secret_key' => $secret_key,
    'otp_recovery_code' => '',
    'w' => '150',
    'h' => '150',
    'cache_dir' => '$base_dir"."cache/',
    'data_dir' => '$base_dir"."data/',
    'includes_dir' => '$base_dir"."includes/',
    'content_dir' => '$base_dir"."content/',
    'stat_dir' => '$data_dir"."stat/',
    'box_token_file' => '$base_dir"."box_token.php',
    'cc_url' => 'http://creativecommons.org/licenses/',
    'cc_ver' => '3.0',
  ),
);
?>
