<?php
return array(
    'site_name',
    'site_description',
    'base_url',
    'base_dir',
    'disqus_shortname',
    'limit',
    'expire_image',
    'expire_session',
    'https',
    'cache_expire',
    'cache_clean',
    'client_id',
    'client_secret',
    'box_root_folder_id',
    'username',
    'email',
    'home_page',
    'password',
    'google_auth',
    'general_access_code',
    'retry',
    'lock_timeout'
  );
?>
