<?php
return array(
  'mandatory' => array(
    'site_name',
    'client_id',
    'client_secret',
    'username',
    'email',
    'password',
    'general_access_code',
    'secret_key',
  ),
  'optional' => array(
    'home_page' => '',
    'disqus_shortname' => '',
    'cdn_url' => '',
    'cover_id' => '',
    'otp_recovery_code' => '',
    'custom_license' => '',
    'custom_license_url' => '',
  ),
  'preset' => array(
    'site_description' => 'Just another mellery site',
    'theme' => 1,
    'order' => 1,
    'limit' => '25',
    'embed_max' => '10',
    'expire_image' => '86400',
    'expire_session' => '1800',
    'expire_access_code' => '24',
    'https' => '0',
    'cache_expire' => '1',
    'usemap' => '1',
    'show_private' => '1',
    'show_viewcount' => '1',
    'cache_clean' => '1',
    'retry' => '5',
    'lock_timeout' => '60',
    'use_cdn' => '0',
    'thumb_cdn' => '1',
    'license' => '0',
    'sa' => '0',
    'nc' => '0',
    'allow_se' => '1',
    'default_public' => '0',
    'admin_folder_limit' => '10',
    'otp_auth' => '0',
    'box_root_folder_id' => '0',
  ),
);
?>
